# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'arc_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(732, 452)
        self.ledt_arc_x = QtWidgets.QLineEdit(Form)
        self.ledt_arc_x.setGeometry(QtCore.QRect(30, 50, 113, 22))
        self.ledt_arc_x.setObjectName("ledt_arc_x")
        self.ledt_arc_y = QtWidgets.QLineEdit(Form)
        self.ledt_arc_y.setGeometry(QtCore.QRect(30, 120, 113, 22))
        self.ledt_arc_y.setObjectName("ledt_arc_y")
        self.ledt_line_lamb = QtWidgets.QLineEdit(Form)
        self.ledt_line_lamb.setGeometry(QtCore.QRect(30, 260, 113, 22))
        self.ledt_line_lamb.setObjectName("ledt_line_lamb")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(30, 160, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.graphWidget = PlotWidget(Form)
        self.graphWidget.setGeometry(QtCore.QRect(180, 10, 501, 381))
        self.graphWidget.setObjectName("graphWidget")
        self.ledt_arc_r = QtWidgets.QLineEdit(Form)
        self.ledt_arc_r.setGeometry(QtCore.QRect(30, 190, 113, 22))
        self.ledt_arc_r.setObjectName("ledt_arc_r")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(30, 20, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(30, 230, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(30, 90, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.btn_graficar = QtWidgets.QPushButton(Form)
        self.btn_graficar.setGeometry(QtCore.QRect(40, 350, 101, 51))
        self.btn_graficar.setObjectName("btn_graficar")
        self.rbtn_superior = QtWidgets.QRadioButton(Form)
        self.rbtn_superior.setGeometry(QtCore.QRect(30, 290, 95, 20))
        self.rbtn_superior.setChecked(True)
        self.rbtn_superior.setObjectName("rbtn_superior")
        self.rbtn_inferior = QtWidgets.QRadioButton(Form)
        self.rbtn_inferior.setGeometry(QtCore.QRect(30, 310, 95, 20))
        self.rbtn_inferior.setObjectName("rbtn_inferior")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "Radio"))
        self.label.setText(_translate("Form", "Coordenada en x"))
        self.label_4.setText(_translate("Form", "Lambda"))
        self.label_2.setText(_translate("Form", "Coordenada en y"))
        self.btn_graficar.setText(_translate("Form", "Graficar"))
        self.rbtn_superior.setText(_translate("Form", "Superior"))
        self.rbtn_inferior.setText(_translate("Form", "Inferior"))
from pyqtgraph import PlotWidget
