# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'line_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LineForm(object):
    def setupUi(self, LineForm):
        LineForm.setObjectName("LineForm")
        LineForm.resize(735, 458)
        self.btn_graficar = QtWidgets.QPushButton(LineForm)
        self.btn_graficar.setGeometry(QtCore.QRect(40, 360, 101, 51))
        self.btn_graficar.setObjectName("btn_graficar")
        self.label_5 = QtWidgets.QLabel(LineForm)
        self.label_5.setGeometry(QtCore.QRect(30, 300, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.ledt_line_lamb = QtWidgets.QLineEdit(LineForm)
        self.ledt_line_lamb.setGeometry(QtCore.QRect(30, 320, 113, 22))
        self.ledt_line_lamb.setObjectName("ledt_line_lamb")
        self.label_4 = QtWidgets.QLabel(LineForm)
        self.label_4.setGeometry(QtCore.QRect(30, 240, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(LineForm)
        self.label_3.setGeometry(QtCore.QRect(30, 170, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(LineForm)
        self.label.setGeometry(QtCore.QRect(30, 30, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(LineForm)
        self.label_2.setGeometry(QtCore.QRect(30, 100, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.ledt_line_y1 = QtWidgets.QLineEdit(LineForm)
        self.ledt_line_y1.setGeometry(QtCore.QRect(30, 270, 113, 22))
        self.ledt_line_y1.setObjectName("ledt_line_y1")
        self.ledt_line_x1 = QtWidgets.QLineEdit(LineForm)
        self.ledt_line_x1.setGeometry(QtCore.QRect(30, 200, 113, 22))
        self.ledt_line_x1.setObjectName("ledt_line_x1")
        self.ledt_line_y0 = QtWidgets.QLineEdit(LineForm)
        self.ledt_line_y0.setGeometry(QtCore.QRect(30, 130, 113, 22))
        self.ledt_line_y0.setObjectName("ledt_line_y0")
        self.ledt_line_x0 = QtWidgets.QLineEdit(LineForm)
        self.ledt_line_x0.setGeometry(QtCore.QRect(30, 60, 113, 22))
        self.ledt_line_x0.setObjectName("ledt_line_x0")
        self.graphWidget = PlotWidget(LineForm)
        self.graphWidget.setGeometry(QtCore.QRect(180, 20, 501, 381))
        self.graphWidget.setObjectName("graphWidget")

        self.retranslateUi(LineForm)
        QtCore.QMetaObject.connectSlotsByName(LineForm)

    def retranslateUi(self, LineForm):
        _translate = QtCore.QCoreApplication.translate
        LineForm.setWindowTitle(_translate("LineForm", "Form"))
        self.btn_graficar.setText(_translate("LineForm", "Graficar"))
        self.label_5.setText(_translate("LineForm", "Lambda"))
        self.label_4.setText(_translate("LineForm", "Posición final y"))
        self.label_3.setText(_translate("LineForm", "Posición final x"))
        self.label.setText(_translate("LineForm", "Posición inicial x"))
        self.label_2.setText(_translate("LineForm", "Posición inicial y"))
from pyqtgraph import PlotWidget
