# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'parabola_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormParabola(object):
    def setupUi(self, FormParabola):
        FormParabola.setObjectName("FormParabola")
        FormParabola.resize(732, 452)
        self.ledt_par_x = QtWidgets.QLineEdit(FormParabola)
        self.ledt_par_x.setGeometry(QtCore.QRect(30, 50, 113, 22))
        self.ledt_par_x.setObjectName("ledt_par_x")
        self.ledt_par_y = QtWidgets.QLineEdit(FormParabola)
        self.ledt_par_y.setGeometry(QtCore.QRect(30, 100, 113, 22))
        self.ledt_par_y.setObjectName("ledt_par_y")
        self.ledt_line_lamb = QtWidgets.QLineEdit(FormParabola)
        self.ledt_line_lamb.setGeometry(QtCore.QRect(30, 200, 113, 22))
        self.ledt_line_lamb.setObjectName("ledt_line_lamb")
        self.label_3 = QtWidgets.QLabel(FormParabola)
        self.label_3.setGeometry(QtCore.QRect(30, 120, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.graphWidget = PlotWidget(FormParabola)
        self.graphWidget.setGeometry(QtCore.QRect(180, 10, 501, 381))
        self.graphWidget.setObjectName("graphWidget")
        self.ledt_dist_foc = QtWidgets.QLineEdit(FormParabola)
        self.ledt_dist_foc.setGeometry(QtCore.QRect(30, 150, 113, 22))
        self.ledt_dist_foc.setObjectName("ledt_dist_foc")
        self.label = QtWidgets.QLabel(FormParabola)
        self.label.setGeometry(QtCore.QRect(30, 20, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(FormParabola)
        self.label_4.setGeometry(QtCore.QRect(30, 180, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_2 = QtWidgets.QLabel(FormParabola)
        self.label_2.setGeometry(QtCore.QRect(30, 70, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.btn_graficar = QtWidgets.QPushButton(FormParabola)
        self.btn_graficar.setGeometry(QtCore.QRect(40, 350, 101, 51))
        self.btn_graficar.setObjectName("btn_graficar")
        self.rbtn_ver_arriba = QtWidgets.QRadioButton(FormParabola)
        self.rbtn_ver_arriba.setGeometry(QtCore.QRect(30, 230, 151, 20))
        self.rbtn_ver_arriba.setChecked(True)
        self.rbtn_ver_arriba.setObjectName("rbtn_ver_arriba")
        self.rbtn_ver_abajo = QtWidgets.QRadioButton(FormParabola)
        self.rbtn_ver_abajo.setGeometry(QtCore.QRect(30, 250, 141, 20))
        self.rbtn_ver_abajo.setObjectName("rbtn_ver_abajo")
        self.rbtn_hor_der = QtWidgets.QRadioButton(FormParabola)
        self.rbtn_hor_der.setGeometry(QtCore.QRect(30, 270, 141, 20))
        self.rbtn_hor_der.setObjectName("rbtn_hor_der")
        self.rbtn_hor_izq = QtWidgets.QRadioButton(FormParabola)
        self.rbtn_hor_izq.setGeometry(QtCore.QRect(30, 290, 141, 20))
        self.rbtn_hor_izq.setObjectName("rbtn_hor_izq")

        self.retranslateUi(FormParabola)
        QtCore.QMetaObject.connectSlotsByName(FormParabola)

    def retranslateUi(self, FormParabola):
        _translate = QtCore.QCoreApplication.translate
        FormParabola.setWindowTitle(_translate("FormParabola", "Form"))
        self.label_3.setText(_translate("FormParabola", "Distancia focal"))
        self.label.setText(_translate("FormParabola", "Coordenada en x"))
        self.label_4.setText(_translate("FormParabola", "Lambda"))
        self.label_2.setText(_translate("FormParabola", "Coordenada en y"))
        self.btn_graficar.setText(_translate("FormParabola", "Graficar"))
        self.rbtn_ver_arriba.setText(_translate("FormParabola", "Vertical hacia arriba"))
        self.rbtn_ver_abajo.setText(_translate("FormParabola", "Vertical hacia abajo"))
        self.rbtn_hor_der.setText(_translate("FormParabola", "Horizontal derecha"))
        self.rbtn_hor_izq.setText(_translate("FormParabola", "Horizontal izquierda"))
from pyqtgraph import PlotWidget
