# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'spline_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormSpline(object):
    def setupUi(self, FormSpline):
        FormSpline.setObjectName("FormSpline")
        FormSpline.resize(731, 451)
        self.label = QtWidgets.QLabel(FormSpline)
        self.label.setGeometry(QtCore.QRect(30, 20, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(FormSpline)
        self.label_3.setGeometry(QtCore.QRect(30, 140, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.ledt_p1 = QtWidgets.QLineEdit(FormSpline)
        self.ledt_p1.setGeometry(QtCore.QRect(30, 50, 113, 22))
        self.ledt_p1.setObjectName("ledt_p1")
        self.label_4 = QtWidgets.QLabel(FormSpline)
        self.label_4.setGeometry(QtCore.QRect(30, 260, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_2 = QtWidgets.QLabel(FormSpline)
        self.label_2.setGeometry(QtCore.QRect(30, 80, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.btn_graficar = QtWidgets.QPushButton(FormSpline)
        self.btn_graficar.setGeometry(QtCore.QRect(40, 350, 101, 51))
        self.btn_graficar.setObjectName("btn_graficar")
        self.ledt_line_lamb = QtWidgets.QLineEdit(FormSpline)
        self.ledt_line_lamb.setGeometry(QtCore.QRect(30, 290, 113, 22))
        self.ledt_line_lamb.setObjectName("ledt_line_lamb")
        self.graphWidget = PlotWidget(FormSpline)
        self.graphWidget.setGeometry(QtCore.QRect(180, 10, 501, 381))
        self.graphWidget.setObjectName("graphWidget")
        self.ledt_p2 = QtWidgets.QLineEdit(FormSpline)
        self.ledt_p2.setGeometry(QtCore.QRect(30, 110, 113, 22))
        self.ledt_p2.setObjectName("ledt_p2")
        self.ledt_p3 = QtWidgets.QLineEdit(FormSpline)
        self.ledt_p3.setGeometry(QtCore.QRect(30, 170, 113, 22))
        self.ledt_p3.setObjectName("ledt_p3")
        self.ledt_p4 = QtWidgets.QLineEdit(FormSpline)
        self.ledt_p4.setGeometry(QtCore.QRect(30, 230, 113, 22))
        self.ledt_p4.setObjectName("ledt_p4")
        self.label_5 = QtWidgets.QLabel(FormSpline)
        self.label_5.setGeometry(QtCore.QRect(30, 200, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")

        self.retranslateUi(FormSpline)
        QtCore.QMetaObject.connectSlotsByName(FormSpline)

    def retranslateUi(self, FormSpline):
        _translate = QtCore.QCoreApplication.translate
        FormSpline.setWindowTitle(_translate("FormSpline", "Form"))
        self.label.setText(_translate("FormSpline", "Punto 1"))
        self.label_3.setText(_translate("FormSpline", "Punto 3"))
        self.label_4.setText(_translate("FormSpline", "Lambda"))
        self.label_2.setText(_translate("FormSpline", "Punto 2"))
        self.btn_graficar.setText(_translate("FormSpline", "Graficar"))
        self.label_5.setText(_translate("FormSpline", "Punto 4"))
from pyqtgraph import PlotWidget
